import 'tailwindcss/tailwind.css';
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react"
import Navbar from "../components/navbar";

const limit = 0.1;

const Analyze = () => {
    const [opened, setOpened] = useState(-1);
    const [closed, setClosed] = useState(-1);

    useEffect(async () => {
        const fetched = await (await fetch("/api/analyze").catch(null)).json(x => x);
        let currentOpened = 0, currentClosed = 0;
        for (let i = 0; i < fetched[1].length; i++) {
            if (fetched[1][i] > limit)
            {
                if (fetched[2][i] === 1) currentOpened++;
                else currentClosed++;
            }       
        }
        setOpened(currentOpened);
        setClosed(currentClosed);
        console.log(fetched);
    });

    return (
        <>
            <Head>
                <title>Beer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar page="beers" />
            <header className="bg-white shadow">
          <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
           <h1 className="text-3xl font-bold text-gray-900">Beers</h1>
        </div>
      </header>
      <main>
        <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
                <img src={process.env.CAM_IP} alt="image" id="image"/>
                <p>Number of opened: {opened == -1 ? "LOADING" : opened}. Number of closed: {closed == -1 ? "LOADING" : closed}.</p>
      

        </div>
      </main>
 
        </>
    );
}
export default Analyze;